
development:
  email: 'tkannippoyil@suyati.com'
  password: '123456'
  password_confirmation: '123456'

test:
  email: 'admin@prompa.com'
  password: '123456'
  password_confirmation: '123456'

production:
  email: 'admin@prompa.com'
  password: '123456'
  password_confirmation: '123456'
