
development:
  consumer_key: 'KAGIBEWD5SB2JMWD7GQ1TZUHKGTDI0' 
  consumer_secret: 'OB3PLMIJ0EW8CYQHSMAWN20TRMZL4E'

test:
  consumer_key: 'KAGIBEWD5SB2JMWD7GQ1TZUHKGTDI0' 
  consumer_secret: 'OB3PLMIJ0EW8CYQHSMAWN20TRMZL4E'

production:
  consumer_key: 'KAGIBEWD5SB2JMWD7GQ1TZUHKGTDI0' 
  consumer_secret: 'OB3PLMIJ0EW8CYQHSMAWN20TRMZL4E'
